#! /usr/bin/env racket
#lang racket
; vim:ft=racket:

(require (prefix-in  env:  web-server/servlet-env)
         (prefix-in  log:  web-server/dispatchers/dispatch-log)
         (prefix-in  res:  web-server/configuration/responders))

(require (prefix-in app: "app.rkt"))

;; TODO SSL
;; TODO Consider app interface/implementation unit.

(module+ main
  ; TODO CLI opts: port-num, log-file
  (let ([program (path->string (find-system-path 'run-file))]
        [paths-to-serve '()]
        [dev? #f])
    (command-line
      #:program program
      #:once-each
      [("-d" "--dev")
       "Development mode: open browser, show stack traces, etc."
       (set! dev? #t)]
      #:args (path . paths)
      (set! paths-to-serve (cons path paths)))
    (env:serve/servlet
      app:dispatch
      #:launch-browser? dev?
      #:extra-files-paths paths-to-serve
      #:file-not-found-responder app:handle-error-not-found
      #:servlet-responder
      (if dev?
          res:servlet-error-responder
          app:handle-error-crash)
      #:servlet-loading-responder
      (if dev?
          res:servlet-loading-responder
          app:handle-error-crash)
      #:log-file (string-append program ".log")
      #:log-format log:paren-format
      #:servlet-path ""
      #:servlet-regexp #rx"")))
