[package]
name = "hfod-web-pub"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
hfod-web-lib = { path = "../lib" }
serde = { workspace = true }
serde_json5 = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
